import type { LessonRequest, TutorProfile } from "./types";

export const SUBJECTS = [
  "Toán",
  "Vật lý",
  "Hóa học",
  "Tiếng Anh",
  "Văn học",
  "Lập trình",
  "Sinh học",
  "Lịch sử",
];

export const LOCATIONS = [
  "Hà Nội",
  "TP. Hồ Chí Minh",
  "Đà Nẵng",
  "Cần Thơ",
  "Hải Phòng",
  "Online",
];

export const MOCK_TUTORS: TutorProfile[] = [
  {
    id: "t1",
    userId: "u1",
    fullName: "Nguyễn Văn An",
    email: "an.nguyen@example.com",
    phone: "0912 345 678",
    gender: "Nam",
    education: "Đại học Sư phạm Hà Nội (Khoa Toán - Cử nhân)",
    teachingMode: "both",
    bio: "Gia sư Toán 10 năm kinh nghiệm, chuyên luyện thi vào 10 và THPT Quốc gia. Nhiều học sinh đỗ trường chuyên, trường điểm.",
    subjects: ["Toán", "Vật lý"],
    targetGrades: ["Lớp 9 (Luyện thi vào 10)", "Lớp 12 (Ôn thi THPT QG)"],
    location: "Hà Nội",
    hourlyRate: 250000,
    experience: 10,
    rating: 4.9,
    reviewCount: 128,
    isVerified: true,
    status: "approved",
    appliedAt: "2026-08-01T08:00:00Z",
    activeStudents: 6,
  },
  {
    id: "t2",
    userId: "u2",
    fullName: "Trần Thị Bình",
    email: "binh.tran@example.com",
    phone: "0987 654 321",
    gender: "Nữ",
    education: "Đại học Sư phạm TP.HCM (Ngôn ngữ Anh - Thạc sĩ)",
    teachingMode: "both",
    bio: "Cử nhân Sư phạm Tiếng Anh, IELTS 8.0, phương pháp giao tiếp tự nhiên và luyện thi cấp tốc.",
    subjects: ["Tiếng Anh"],
    targetGrades: ["THCS (Lớp 6-8)", "Luyện thi IELTS/TOEIC"],
    location: "TP. Hồ Chí Minh",
    hourlyRate: 200000,
    experience: 6,
    rating: 4.8,
    reviewCount: 95,
    isVerified: true,
    status: "approved",
    appliedAt: "2026-08-05T09:30:00Z",
    activeStudents: 8,
  },
  {
    id: "t3",
    userId: "u3",
    fullName: "Lê Minh Cường",
    email: "cuong.le@example.com",
    phone: "0903 112 233",
    gender: "Nam",
    education: "Đại học Bách Khoa Hà Nội (CNTT - Kỹ sư)",
    teachingMode: "online",
    bio: "Kỹ sư phần mềm, dạy lập trình Python, JavaScript cho học sinh và sinh viên. Ôn thi Tin học trẻ.",
    subjects: ["Lập trình", "Toán"],
    targetGrades: [
      "Tiểu học (Lớp 1-5)",
      "THCS (Lớp 6-8)",
      "Người đi làm / Sinh viên",
    ],
    location: "Online",
    hourlyRate: 300000,
    experience: 5,
    rating: 4.7,
    reviewCount: 67,
    isVerified: false,
    status: "pending",
    appliedAt: "2026-08-18T14:15:00Z",
    activeStudents: 2,
  },
  {
    id: "t4",
    userId: "u4",
    fullName: "Phạm Thu Hà",
    email: "ha.pham@example.com",
    phone: "0934 556 778",
    gender: "Nữ",
    education: "Đại học Sư phạm Đà Nẵng (Hóa học - Cử nhân)",
    teachingMode: "both",
    bio: "Giáo viên Hóa học trường THPT chuyên, nhiệt tình, có phương pháp giải nhanh trắc nghiệm.",
    subjects: ["Hóa học", "Sinh học"],
    targetGrades: ["THPT (Lớp 10-11)", "Lớp 12 (Ôn thi THPT QG)"],
    location: "Đà Nẵng",
    hourlyRate: 220000,
    experience: 8,
    rating: 4.9,
    reviewCount: 84,
    isVerified: true,
    status: "approved",
    appliedAt: "2026-08-08T11:00:00Z",
    activeStudents: 5,
  },
  {
    id: "t5",
    userId: "u5",
    fullName: "Hoàng Đức Nam",
    email: "nam.hoang@example.com",
    phone: "0971 889 900",
    gender: "Nam",
    education: "Đại học Cần Thơ (Sư phạm Vật lý)",
    teachingMode: "offline",
    bio: "Sinh viên năm cuối ngành Sư phạm Lý, đạt giải Nhì Olympic Vật lý Sinh viên, kiên nhẫn giảng bài.",
    subjects: ["Vật lý", "Toán"],
    targetGrades: ["THCS (Lớp 6-8)", "THPT (Lớp 10-11)"],
    location: "Cần Thơ",
    hourlyRate: 180000,
    experience: 3,
    rating: 4.6,
    reviewCount: 24,
    isVerified: false,
    status: "pending",
    appliedAt: "2026-08-21T16:45:00Z",
    activeStudents: 0,
  },
  {
    id: "t6",
    userId: "u6",
    fullName: "Vũ Hải Yến",
    email: "haiyen.vu@example.com",
    phone: "0962 334 455",
    gender: "Nữ",
    education: "Đại học Hải Phòng (Sư phạm Ngữ Văn)",
    teachingMode: "both",
    bio: "Giáo viên Ngữ Văn giàu kinh nghiệm, rèn kỹ năng viết luận, cảm thụ văn học và rèn chữ đẹp tiểu học.",
    subjects: ["Văn học"],
    targetGrades: [
      "Tiểu học (Lớp 1-5)",
      "THCS (Lớp 6-8)",
      "Lớp 9 (Luyện thi vào 10)",
    ],
    location: "Hải Phòng",
    hourlyRate: 190000,
    experience: 7,
    rating: 4.8,
    reviewCount: 52,
    isVerified: true,
    status: "approved",
    appliedAt: "2026-08-10T10:00:00Z",
    activeStudents: 4,
  },
];

export const MOCK_LESSONS: LessonRequest[] = [
  {
    id: "l1",
    studentId: "s1",
    studentName: "Hoàng Minh",
    studentPhone: "0901 234 567",
    tutorId: "t1",
    tutorName: "Nguyễn Văn An",
    subject: "Toán",
    message: "Em cần ôn tập chương hàm số trước thi giữa kỳ.",
    preferredDate: "2026-08-20",
    preferredTime: "18:00",
    location: "Cầu Giấy, Hà Nội",
    hourlyRate: 250000,
    status: "pending",
    createdAt: "2026-08-16T10:00:00Z",
    notes: "Học sinh học khá, cần nâng cao phần bài toán thực tế.",
  },
  {
    id: "l2",
    studentId: "s1",
    studentName: "Hoàng Minh",
    studentPhone: "0901 234 567",
    tutorId: "t2",
    tutorName: "Trần Thị Bình",
    subject: "Tiếng Anh",
    message: "Luyện speaking cho kỳ thi IELTS mục tiêu 7.0.",
    preferredDate: "2026-08-22",
    preferredTime: "19:30",
    location: "Quận 3, TP. Hồ Chí Minh",
    hourlyRate: 200000,
    status: "accepted",
    createdAt: "2026-08-14T08:00:00Z",
    notes: "Lớp học định kỳ thứ 3 - thứ 5 hàng tuần.",
  },
  {
    id: "l3",
    studentId: "s2",
    studentName: "Lan Anh",
    studentPhone: "0918 998 877",
    tutorId: "t1",
    tutorName: "Nguyễn Văn An",
    subject: "Vật lý",
    message: "Cần hỗ trợ bài tập dao động điều hòa lớp 12.",
    preferredDate: "2026-08-18",
    preferredTime: "17:00",
    location: "Thanh Xuân, Hà Nội",
    hourlyRate: 250000,
    status: "completed",
    createdAt: "2026-08-10T14:00:00Z",
    notes: "Đã hoàn thành khóa ôn tập 8 buổi, tiến bộ rõ rệt.",
  },
  {
    id: "l4",
    studentId: "s3",
    studentName: "Đức Trọng",
    studentPhone: "0945 667 788",
    tutorId: "t4",
    tutorName: "Phạm Thu Hà",
    subject: "Hóa học",
    message: "Lấy lại gốc Hóa học 11 trước khi vào năm học mới.",
    preferredDate: "2026-08-25",
    preferredTime: "15:00",
    location: "Hải Châu, Đà Nẵng",
    hourlyRate: 220000,
    status: "accepted",
    createdAt: "2026-08-19T09:00:00Z",
    notes: "Phụ huynh yêu cầu theo sát tiến độ hàng tuần.",
  },
  {
    id: "l5",
    studentId: "s4",
    studentName: "Tuấn Kiệt",
    studentPhone: "0932 114 477",
    tutorId: "t3",
    tutorName: "Lê Minh Cường",
    subject: "Lập trình",
    message: "Học lập trình Python cơ bản và thuật toán cho học sinh THCS.",
    preferredDate: "2026-08-26",
    preferredTime: "20:00",
    location: "Online",
    hourlyRate: 300000,
    status: "pending",
    createdAt: "2026-08-21T11:20:00Z",
    notes: "Lớp học trực tuyến qua Google Meet.",
  },
];

// -------------------------------------------------------------
// DỮ LIỆU MẪU DÀNH CHO TRANG GIÁO VIÊN (TUTOR PORTAL)
// -------------------------------------------------------------

export const MOCK_TUTOR_REQUESTS: import("./types").TutorIncomingRequest[] = [
  // Yêu cầu từ Học sinh / Phụ huynh
  {
    id: "req-1",
    senderType: "student",
    senderName: "Trần Minh Khang (Phụ huynh: Chị Mai)",
    senderContact: "0912 888 999",
    senderRoleTitle: "Học sinh Lớp 12 - THPT Yên Hòa",
    avatar: "👨‍🎓",
    title: "Đăng ký học kèm 1-1 môn Toán ôn thi THPT Quốc Gia",
    content:
      "Chào Thầy, em bị hổng kiến thức phần Hình học không gian và Tích phân. Em muốn học 2 buổi/tuần vào các buổi tối để nâng điểm lên 8.5+ ạ.",
    subject: "Toán",
    gradeLevel: "Lớp 12 (Ôn thi ĐH)",
    preferredDate: "Bắt đầu từ tuần này",
    preferredTime: "Thứ 3 & Thứ 6 (19:30 - 21:30)",
    location: "Online qua Google Meet",
    offeredRate: 250000,
    status: "pending",
    createdAt: "2026-09-08T08:30:00Z",
    urgent: true,
  },
  {
    id: "req-2",
    senderType: "student",
    senderName: "Nguyễn Bảo Ngọc",
    senderContact: "0987 112 334",
    senderRoleTitle: "Học sinh Lớp 9 - THCS Cầu Giấy",
    avatar: "👩‍🎓",
    title: "Học thử 01 buổi miễn phí môn Toán vào 10",
    content:
      "Em muốn đặt lịch học thử 01 buổi để Thầy kiểm tra năng lực và tư vấn lộ trình luyện thi vào trường chuyên Sư Phạm ạ.",
    subject: "Toán",
    gradeLevel: "Lớp 9 (Luyện thi vào 10)",
    preferredDate: "2026-09-10",
    preferredTime: "18:00 - 19:30",
    location: "Tại nhà (Nguyễn Khánh Toàn, Cầu Giấy)",
    offeredRate: 250000,
    status: "pending",
    createdAt: "2026-09-07T14:15:00Z",
  },
  // Yêu cầu / Thông báo từ Ban Quản Trị (Admin)
  {
    id: "req-3",
    senderType: "admin",
    senderName: "Ban Điều Phối Lớp EduTutor (Admin)",
    senderContact: "admin@edututor.vn",
    senderRoleTitle: "Quản Trị Viên Trung Tâm",
    avatar: "🛡️",
    title: "Phân công lớp Toán VIP 12 - Học viên: Lê Hoàng Long",
    content:
      "Trung tâm gửi Thầy lớp học kèm VIP 1-1 tại khu vực Cầu Giấy (hoặc Online). Phụ huynh học sinh cam kết học dài hạn 6 tháng, học phí 300.000đ/buổi. Thầy vui lòng duyệt tiếp nhận trước 18h hôm nay.",
    subject: "Toán",
    gradeLevel: "Lớp 12 VIP",
    preferredDate: "Bắt đầu 12/09/2026",
    preferredTime: "Thứ 4 & Chủ Nhật (19:00 - 21:00)",
    location: "Duy Tân, Cầu Giấy, Hà Nội",
    offeredRate: 300000,
    status: "pending",
    createdAt: "2026-09-08T09:00:00Z",
    urgent: true,
  },
  {
    id: "req-4",
    senderType: "admin",
    senderName: "Hệ thống Kiểm duyệt EduTutor",
    senderContact: "support@edututor.vn",
    senderRoleTitle: "Hệ Thống Tự Động",
    avatar: "⭐",
    title: "Chúc mừng: Hồ sơ gia sư của Thầy đã đạt chuẩn Top 5% Yêu Thích!",
    content:
      "Dựa trên đánh giá 4.9★ từ học viên, tài khoản của Thầy đã được ưu tiên hiển thị trên trang chủ và nhận huy hiệu Gia Sư Xuất Sắc.",
    status: "accepted",
    createdAt: "2026-09-05T10:00:00Z",
  },
  // Yêu cầu từ Giáo viên đồng nghiệp / Chuyển nhượng
  {
    id: "req-5",
    senderType: "tutor",
    senderName: "Cô Trần Thị Bình (Gia sư Tiếng Anh)",
    senderContact: "0987 654 321",
    senderRoleTitle: "Gia sư đồng nghiệp EduTutor",
    avatar: "👩‍🏫",
    title: "Nhờ dạy kèm thêm phần Toán cho học sinh của cô",
    content:
      "Chào Thầy An, em đang dạy kèm Tiếng Anh cho bạn Tuấn Anh (lớp 11 THPT Kim Liên), phụ huynh có nhờ em tìm thêm 1 thầy dạy Toán nhiệt tình. Em giới thiệu lớp này cho Thầy nhé!",
    subject: "Toán",
    gradeLevel: "Lớp 11",
    preferredDate: "Thứ 7 hàng tuần",
    preferredTime: "15:00 - 17:00",
    location: "Online",
    offeredRate: 240000,
    status: "pending",
    createdAt: "2026-09-06T16:20:00Z",
  },
];

export const MOCK_TUTOR_SCHEDULE: import("./types").ScheduleSession[] = [
  {
    id: "sch-1",
    studentName: "Hoàng Minh",
    studentPhone: "0901 234 567",
    studentAvatar: "👦",
    subject: "Toán 12",
    gradeLevel: "Lớp 12",
    date: "2026-09-08",
    dayOfWeek: "Hôm nay (Thứ 3)",
    time: "18:00 - 20:00",
    duration: "120 phút",
    location: "Google Meet",
    mode: "online",
    meetingLink: "https://meet.google.com/edu-tutor-math",
    hourlyRate: 250000,
    status: "upcoming",
    notes: "Ôn tập chuyên đề Khảo sát hàm số & Cực trị bài toán thực tế.",
  },
  {
    id: "sch-2",
    studentName: "Lan Anh",
    studentPhone: "0918 998 877",
    studentAvatar: "👧",
    subject: "Vật lý 12",
    gradeLevel: "Lớp 12",
    date: "2026-09-09",
    dayOfWeek: "Ngày mai (Thứ 4)",
    time: "19:30 - 21:30",
    duration: "120 phút",
    location: "Số 18 Thanh Xuân, Hà Nội",
    mode: "offline",
    address: "P402, Chung cư Sapphire, Thanh Xuân, Hà Nội",
    hourlyRate: 250000,
    status: "upcoming",
    notes: "Luyện tập phần Dao động tắt dần & Sóng cơ.",
  },
  {
    id: "sch-3",
    studentName: "Đức Trọng",
    studentPhone: "0945 667 788",
    studentAvatar: "🧑",
    subject: "Toán 11",
    gradeLevel: "Lớp 11",
    date: "2026-09-10",
    dayOfWeek: "Thứ 5",
    time: "18:30 - 20:30",
    duration: "120 phút",
    location: "Google Meet",
    mode: "online",
    meetingLink: "https://meet.google.com/edu-tutor-room2",
    hourlyRate: 220000,
    status: "upcoming",
    notes: "Chữa đề thi giữa kỳ I.",
  },
  {
    id: "sch-4",
    studentName: "Tuấn Kiệt",
    studentPhone: "0932 114 477",
    studentAvatar: "👦",
    subject: "Toán 9 (Luyện vào 10)",
    gradeLevel: "Lớp 9",
    date: "2026-09-11",
    dayOfWeek: "Thứ 6",
    time: "17:30 - 19:30",
    duration: "120 phút",
    location: "Số 85 Cầu Giấy, Hà Nội",
    mode: "offline",
    address: "Số 85 Ngõ 105 Doãn Kế Thiện, Cầu Giấy, Hà Nội",
    hourlyRate: 250000,
    status: "upcoming",
    notes: "Rèn kỹ năng giải Hệ phương trình & Hình học đường tròn.",
  },
  {
    id: "sch-5",
    studentName: "Nguyễn Phương Nhi",
    studentPhone: "0912 555 777",
    studentAvatar: "👧",
    subject: "Toán 10",
    gradeLevel: "Lớp 10",
    date: "2026-09-07",
    dayOfWeek: "Hôm qua (Thứ 2)",
    time: "19:00 - 21:00",
    duration: "120 phút",
    location: "Google Meet",
    mode: "online",
    hourlyRate: 220000,
    status: "completed",
    notes: "Đã hoàn thành buổi học thứ 4, học sinh tiếp thu tốt.",
  },
];

export const MOCK_ADMIN_CHATS: import("./types").ChatMessage[] = [
  {
    id: "msg-1",
    sender: "admin",
    senderName: "Hỗ Trợ Giáo Viên - EduTutor Admin",
    text: "Xin chào Thầy Nguyễn Văn An! Ban Quản Trị EduTutor chúc Thầy một tuần giảng dạy hiệu quả. Thầy cần hỗ trợ bất kỳ vấn đề gì về lớp học hay phụ huynh không ạ?",
    timestamp: "2026-09-08T08:00:00Z",
    isRead: true,
  },
  {
    id: "msg-2",
    sender: "tutor",
    senderName: "Thầy Nguyễn Văn An",
    text: "Chào Admin, tôi vừa nhận được thông báo lớp Toán VIP 12 của bạn Lê Hoàng Long. Tôi đã đồng ý nhận lớp, nhờ trung tâm liên hệ kết nối nhóm Zalo giúp tôi nhé!",
    timestamp: "2026-09-08T09:15:00Z",
    isRead: true,
  },
  {
    id: "msg-3",
    sender: "admin",
    senderName: "Hỗ Trợ Giáo Viên - EduTutor Admin",
    text: "Dạ vâng Thầy, bên em đã gửi số Zalo của phụ huynh và tạo nhóm trao đổi chung rồi ạ. Thầy có thể kiểm tra Zalo nhé. Chúc Thầy dạy tốt ạ!",
    timestamp: "2026-09-08T09:18:00Z",
    isRead: true,
  },
];
