import type { LessonRequest, TutorProfile } from "./types";

export const SUBJECTS = [
  "Toán",
  "Vật lý",
  "Hóa học",
  "Tiếng Anh",
  "Văn học",
  "Lập trình",
  "Sinh học",
  "Lịch sử",
];

export const LOCATIONS = [
  "Hà Nội",
  "TP. Hồ Chí Minh",
  "Đà Nẵng",
  "Cần Thơ",
  "Hải Phòng",
  "Online",
];

export const MOCK_TUTORS: TutorProfile[] = [
  {
    id: "t1",
    userId: "u1",
    fullName: "Nguyễn Văn An",
    email: "an.nguyen@example.com",
    phone: "0912 345 678",
    gender: "Nam",
    education: "Đại học Sư phạm Hà Nội (Khoa Toán - Cử nhân)",
    teachingMode: "both",
    bio: "Gia sư Toán 10 năm kinh nghiệm, chuyên luyện thi vào 10 và THPT Quốc gia. Nhiều học sinh đỗ trường chuyên, trường điểm.",
    subjects: ["Toán", "Vật lý"],
    targetGrades: ["Lớp 9 (Luyện thi vào 10)", "Lớp 12 (Ôn thi THPT QG)"],
    location: "Hà Nội",
    hourlyRate: 250000,
    experience: 10,
    rating: 4.9,
    reviewCount: 128,
    isVerified: true,
    status: "approved",
    appliedAt: "2026-08-01T08:00:00Z",
    activeStudents: 6,
  },
  {
    id: "t2",
    userId: "u2",
    fullName: "Trần Thị Bình",
    email: "binh.tran@example.com",
    phone: "0987 654 321",
    gender: "Nữ",
    education: "Đại học Sư phạm TP.HCM (Ngôn ngữ Anh - Thạc sĩ)",
    teachingMode: "both",
    bio: "Cử nhân Sư phạm Tiếng Anh, IELTS 8.0, phương pháp giao tiếp tự nhiên và luyện thi cấp tốc.",
    subjects: ["Tiếng Anh"],
    targetGrades: ["THCS (Lớp 6-8)", "Luyện thi IELTS/TOEIC"],
    location: "TP. Hồ Chí Minh",
    hourlyRate: 200000,
    experience: 6,
    rating: 4.8,
    reviewCount: 95,
    isVerified: true,
    status: "approved",
    appliedAt: "2026-08-05T09:30:00Z",
    activeStudents: 8,
  },
  {
    id: "t3",
    userId: "u3",
    fullName: "Lê Minh Cường",
    email: "cuong.le@example.com",
    phone: "0903 112 233",
    gender: "Nam",
    education: "Đại học Bách Khoa Hà Nội (CNTT - Kỹ sư)",
    teachingMode: "online",
    bio: "Kỹ sư phần mềm, dạy lập trình Python, JavaScript cho học sinh và sinh viên. Ôn thi Tin học trẻ.",
    subjects: ["Lập trình", "Toán"],
    targetGrades: [
      "Tiểu học (Lớp 1-5)",
      "THCS (Lớp 6-8)",
      "Người đi làm / Sinh viên",
    ],
    location: "Online",
    hourlyRate: 300000,
    experience: 5,
    rating: 4.7,
    reviewCount: 67,
    isVerified: false,
    status: "pending",
    appliedAt: "2026-08-18T14:15:00Z",
    activeStudents: 2,
  },
  {
    id: "t4",
    userId: "u4",
    fullName: "Phạm Thu Hà",
    email: "ha.pham@example.com",
    phone: "0934 556 778",
    gender: "Nữ",
    education: "Đại học Sư phạm Đà Nẵng (Hóa học - Cử nhân)",
    teachingMode: "both",
    bio: "Giáo viên Hóa học trường THPT chuyên, nhiệt tình, có phương pháp giải nhanh trắc nghiệm.",
    subjects: ["Hóa học", "Sinh học"],
    targetGrades: ["THPT (Lớp 10-11)", "Lớp 12 (Ôn thi THPT QG)"],
    location: "Đà Nẵng",
    hourlyRate: 220000,
    experience: 8,
    rating: 4.9,
    reviewCount: 84,
    isVerified: true,
    status: "approved",
    appliedAt: "2026-08-08T11:00:00Z",
    activeStudents: 5,
  },
  {
    id: "t5",
    userId: "u5",
    fullName: "Hoàng Đức Nam",
    email: "nam.hoang@example.com",
    phone: "0971 889 900",
    gender: "Nam",
    education: "Đại học Cần Thơ (Sư phạm Vật lý)",
    teachingMode: "offline",
    bio: "Sinh viên năm cuối ngành Sư phạm Lý, đạt giải Nhì Olympic Vật lý Sinh viên, kiên nhẫn giảng bài.",
    subjects: ["Vật lý", "Toán"],
    targetGrades: ["THCS (Lớp 6-8)", "THPT (Lớp 10-11)"],
    location: "Cần Thơ",
    hourlyRate: 180000,
    experience: 3,
    rating: 4.6,
    reviewCount: 24,
    isVerified: false,
    status: "pending",
    appliedAt: "2026-08-21T16:45:00Z",
    activeStudents: 0,
  },
  {
    id: "t6",
    userId: "u6",
    fullName: "Vũ Hải Yến",
    email: "haiyen.vu@example.com",
    phone: "0962 334 455",
    gender: "Nữ",
    education: "Đại học Hải Phòng (Sư phạm Ngữ Văn)",
    teachingMode: "both",
    bio: "Giáo viên Ngữ Văn giàu kinh nghiệm, rèn kỹ năng viết luận, cảm thụ văn học và rèn chữ đẹp tiểu học.",
    subjects: ["Văn học"],
    targetGrades: [
      "Tiểu học (Lớp 1-5)",
      "THCS (Lớp 6-8)",
      "Lớp 9 (Luyện thi vào 10)",
    ],
    location: "Hải Phòng",
    hourlyRate: 190000,
    experience: 7,
    rating: 4.8,
    reviewCount: 52,
    isVerified: true,
    status: "approved",
    appliedAt: "2026-08-10T10:00:00Z",
    activeStudents: 4,
  },
];

export const MOCK_LESSONS: LessonRequest[] = [
  {
    id: "l1",
    studentId: "s1",
    studentName: "Hoàng Minh",
    studentPhone: "0901 234 567",
    tutorId: "t1",
    tutorName: "Nguyễn Văn An",
    subject: "Toán",
    message: "Em cần ôn tập chương hàm số trước thi giữa kỳ.",
    preferredDate: "2026-08-20",
    preferredTime: "18:00",
    location: "Cầu Giấy, Hà Nội",
    hourlyRate: 250000,
    status: "pending",
    createdAt: "2026-08-16T10:00:00Z",
    notes: "Học sinh học khá, cần nâng cao phần bài toán thực tế.",
  },
  {
    id: "l2",
    studentId: "s1",
    studentName: "Hoàng Minh",
    studentPhone: "0901 234 567",
    tutorId: "t2",
    tutorName: "Trần Thị Bình",
    subject: "Tiếng Anh",
    message: "Luyện speaking cho kỳ thi IELTS mục tiêu 7.0.",
    preferredDate: "2026-08-22",
    preferredTime: "19:30",
    location: "Quận 3, TP. Hồ Chí Minh",
    hourlyRate: 200000,
    status: "accepted",
    createdAt: "2026-08-14T08:00:00Z",
    notes: "Lớp học định kỳ thứ 3 - thứ 5 hàng tuần.",
  },
  {
    id: "l3",
    studentId: "s2",
    studentName: "Lan Anh",
    studentPhone: "0918 998 877",
    tutorId: "t1",
    tutorName: "Nguyễn Văn An",
    subject: "Vật lý",
    message: "Cần hỗ trợ bài tập dao động điều hòa lớp 12.",
    preferredDate: "2026-08-18",
    preferredTime: "17:00",
    location: "Thanh Xuân, Hà Nội",
    hourlyRate: 250000,
    status: "completed",
    createdAt: "2026-08-10T14:00:00Z",
    notes: "Đã hoàn thành khóa ôn tập 8 buổi, tiến bộ rõ rệt.",
  },
  {
    id: "l4",
    studentId: "s3",
    studentName: "Đức Trọng",
    studentPhone: "0945 667 788",
    tutorId: "t4",
    tutorName: "Phạm Thu Hà",
    subject: "Hóa học",
    message: "Lấy lại gốc Hóa học 11 trước khi vào năm học mới.",
    preferredDate: "2026-08-25",
    preferredTime: "15:00",
    location: "Hải Châu, Đà Nẵng",
    hourlyRate: 220000,
    status: "accepted",
    createdAt: "2026-08-19T09:00:00Z",
    notes: "Phụ huynh yêu cầu theo sát tiến độ hàng tuần.",
  },
  {
    id: "l5",
    studentId: "s4",
    studentName: "Tuấn Kiệt",
    studentPhone: "0932 114 477",
    tutorId: "t3",
    tutorName: "Lê Minh Cường",
    subject: "Lập trình",
    message: "Học lập trình Python cơ bản và thuật toán cho học sinh THCS.",
    preferredDate: "2026-08-26",
    preferredTime: "20:00",
    location: "Online",
    hourlyRate: 300000,
    status: "pending",
    createdAt: "2026-08-21T11:20:00Z",
    notes: "Lớp học trực tuyến qua Google Meet.",
  },
];
